remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins:
- jekyll-remote-theme
title: Poor Thing
description: A document housing the backstory and related links/articles for ONE OF the stories in Poor Thing's background.
